### ISSUE TITLE
Custom equations

### ISSUE THREAD

**Issue by JulianKunkel** [VI4IO/io-500-webpage#8]
Custom equations worked in the past, e.g.: io500.score / information.client_nodes
https://www.vi4io.org/io500/list/19-11/full

Tried here various options: https://www.jbez.io500.org/site/releases/customize
Lead to server error.

Just want to know if it works at all. We can disable the feature.

**Comment by johnbent** [comment]
I just tried and it works if you use the labels as shown in the window.  If you use the labels from existing webpage, they don't always match exactly and there is not a great error message.  Jean Luca, can you make it so that their is better error handling please?  Maybe, "Sorry, there is no such field 'foobar', did you mean 'information_client_nodes' perhaps?"

![image](https://user-images.githubusercontent.com/2047294/87194276-73bfaf80-c2b6-11ea-8a06-7781aaa6b6f9.png)

**Comment by jeanbez** [comment]
The last commit handle errors in the equations. @JulianKunkel could you please try again and see if it works as expected?

**Comment by adilger** [comment]
I tried to use a custom equation "io500_score / information_client_total_procs", but it kept reporting an error "Sorry, but 'information_client_total_procs' is not known." I'm pretty sure I'm using the correct variable names.

**Comment by jeanbez** [comment]
@adilger some of the fields were not being considered in the equation. This has been fixed in the last commit. Thanks for reporting!
